name: Publish Docker
on: [push]
jobs:
  test:
    steps:
      - uses: actions/checkout@master
      - name: Run tests
        run: |
          yarn && yarn test:ci
      - uses: codecov/codecov-action@v2

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: msosnov/pomodoro-app
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy to Portainer
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.PORTAINER_WEBHOOK_URL }}
          data: ''
